# Generated by Django 5.2.15 on 2026-07-07 20:21

import apps.learning.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.learning.models.generate_session_token, max_length=64, unique=True)),
                ('current_module_id', models.PositiveIntegerField(default=1)),
                ('current_task_id', models.CharField(blank=True, max_length=80)),
                ('aggregate_mastery', models.FloatField(default=70.0)),
                ('aggregate_friction', models.FloatField(default=25.0)),
                ('completed_task_count', models.PositiveIntegerField(default=0)),
                ('latest_recommendation', models.CharField(default='hold_current_tier', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=80)),
                ('module_id', models.PositiveIntegerField()),
                ('task_type', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('difficulty_level', models.PositiveSmallIntegerField()),
                ('task_metric_weight', models.FloatField()),
                ('baseline_time_seconds', models.PositiveIntegerField()),
                ('elapsed_time_seconds', models.FloatField()),
                ('relative_response_time', models.FloatField()),
                ('assistance_interactions', models.PositiveIntegerField(default=0)),
                ('completion_ratio', models.FloatField(default=1.0)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answer_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.learnersession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MicroSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_score', models.PositiveSmallIntegerField()),
                ('perceived_difficulty', models.PositiveSmallIntegerField()),
                ('confidence_score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_surveys', to='learning.learnersession')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_surveys', to='learning.tasksubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuzzyEvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_snapshot', models.JSONField(default=dict)),
                ('engine_trace', models.JSONField(default=dict)),
                ('knowledge_mastery', models.FloatField()),
                ('system_cognitive_friction', models.FloatField()),
                ('focus_state', models.CharField(max_length=80)),
                ('recommendation', models.CharField(max_length=80)),
                ('support_message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuzzy_logs', to='learning.learnersession')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuzzy_log', to='learning.tasksubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['session', 'created_at'], name='learning_ta_session_797896_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['task_id'], name='learning_ta_task_id_c86915_idx'),
        ),
        migrations.AddIndex(
            model_name='fuzzyevaluationlog',
            index=models.Index(fields=['session', 'created_at'], name='learning_fu_session_18ce7b_idx'),
        ),
        migrations.AddIndex(
            model_name='fuzzyevaluationlog',
            index=models.Index(fields=['recommendation'], name='learning_fu_recomme_5a9c29_idx'),
        ),
    ]
