from .base import code, mcq


TASKS = [
    mcq(
        "arrays-mcq-001", "foundation", 60,
        "Why can array lookups by index be fast?",
        ["memory layout", "indexing"],
        ["The location can be computed directly", "Arrays always sort values", "Indexes scan from the start", "Every value is duplicated"],
        "The location can be computed directly",
        "A fixed-size element's address can be calculated from the base address and index offset.",
        [
            "Think about locating a position without searching earlier values.",
            "A predictable element size makes an offset computable.",
            "Choose the property that enables direct indexed access.",
        ],
    ),
    mcq(
        "arrays-mcq-003", "foundation", 55,
        "For values = [10, 20, 30], which expression reads 30?",
        ["indexing", "zero-based index"],
        ["values[2]", "values[3]", "values[1]", "values[-4]"],
        "values[2]",
        "With zero-based indexing, the third element is at index 2.",
        [
            "Count positions beginning with zero.",
            "The indexes are 0, 1, and 2.",
            "Match the last valid positive index to the value 30.",
        ],
    ),
    code(
        "arrays-code-002", "foundation", 70,
        "Create values containing 5, 10, and 15, then store its length in size.",
        ["array creation", "length"],
        "values = []\nsize = 0\n",
        "Use a list literal and len(values).",
        "The sequence has three elements, so size becomes 3.",
        [
            "Place the requested numbers in a list in the same order.",
            "Python's len() reports the number of elements.",
            "Complete values = [__, __, __] and size = len(values).",
        ],
    ),
    code(
        "arrays-code-003", "foundation", 75,
        "Replace the second element of values with 99.",
        ["index assignment", "mutation"],
        "values = [10, 20, 30]\n",
        "Assign 99 to values[1].",
        "The second position has index 1, producing [10, 99, 30].",
        [
            "Use indexed assignment rather than append.",
            "The second position has a zero-based index of one.",
            "Complete values[__] = 99.",
        ],
    ),
    code(
        "arrays-code-004", "foundation", 75,
        "Store the last element of readings in a variable named latest.",
        ["negative indexing", "array access"],
        "readings = [12, 15, 18]\nlatest = None\n",
        "Use readings[-1].",
        "Index -1 addresses the final element regardless of the sequence length.",
        [
            "Python supports indexes measured backward from the end.",
            "The last item uses the first negative index.",
            "Complete latest = readings[__].",
        ],
    ),
    mcq(
        "arrays-mcq-004", "intermediate", 70,
        "What is the typical time complexity of reading an array element by index?",
        ["complexity", "random access"],
        ["O(1)", "O(n)", "O(log n)", "O(n²)"],
        "O(1)",
        "Direct address calculation makes indexed access constant time.",
        [
            "The operation does not depend on scanning the array length.",
            "Its work remains approximately the same as n grows.",
            "Choose the constant-time complexity notation.",
        ],
    ),
    mcq(
        "arrays-mcq-005", "intermediate", 75,
        "Why is inserting into the middle of a contiguous array often O(n)?",
        ["insertion", "shifting", "complexity"],
        ["Later elements may need shifting", "The array must be sorted", "Indexes must be hashed", "Every element is compared twice"],
        "Later elements may need shifting",
        "Opening a middle position can require moving a linear number of subsequent elements.",
        [
            "Consider what occupies the position where the new item must go.",
            "Contiguous layout must be preserved after insertion.",
            "Elements following the insertion point may each move one place.",
        ],
    ),
    code(
        "arrays-code-001", "intermediate", 80,
        "Store 10, 20, and 30 in values and print the first item.",
        ["array access", "indexing"],
        "values = []\n",
        "Create the list and use print(values[0]).",
        "The first item is accessed at index 0.",
        [
            "Python sequences use zero-based indexing.",
            "Create the values in order, then pass the first indexed element to print().",
            "Complete values = [__, __, __] followed by print(values[__]).",
        ],
    ),
    code(
        "arrays-code-005", "intermediate", 95,
        "Compute the sum of the numeric values without using sum() and store it in total.",
        ["iteration", "accumulator"],
        "values = [4, 7, 2, 9]\ntotal = 0\n",
        "Loop over values and add each element to total.",
        "An accumulator initialized to zero produces a total of 22.",
        [
            "Keep a running result while visiting each element.",
            "Addition has an identity value of zero.",
            "Use for value in values: total += value.",
        ],
    ),
    code(
        "arrays-code-006", "intermediate", 100,
        "Find the largest value without using max() and store it in largest.",
        ["linear scan", "comparison"],
        "values = [8, 3, 14, 6]\nlargest = values[0]\n",
        "Scan the remaining elements and replace largest whenever a bigger value appears.",
        "A single linear scan retains 14 as the largest value.",
        [
            "Start with a real element rather than an arbitrary sentinel.",
            "Compare every later value with the best value seen so far.",
            "Use if value > largest: largest = value inside a loop.",
        ],
    ),
    mcq(
        "arrays-mcq-002", "advanced", 80,
        "Which operation is usually expensive for a fixed-size contiguous array?",
        ["insertion cost", "memory shift"],
        ["Inserting at the front", "Reading by index", "Checking length", "Reading the last value"],
        "Inserting at the front",
        "A front insertion can require shifting all existing elements.",
        [
            "Compare inspection operations with an operation that changes positions.",
            "Making space near the beginning affects later elements.",
            "Choose the operation that may shift almost the entire array.",
        ],
    ),
    mcq(
        "arrays-mcq-006", "advanced", 90,
        "What does row-major storage mean for a two-dimensional array?",
        ["row-major", "memory layout"],
        ["Elements of each row are adjacent", "Elements are stored randomly", "Columns must be sorted", "Only diagonal values are stored"],
        "Elements of each row are adjacent",
        "Row-major layout stores one complete row contiguously before the next row.",
        [
            "The term identifies which dimension varies fastest in memory.",
            "Finish one horizontal sequence before moving to the next.",
            "Choose the option describing adjacent values from the same row.",
        ],
    ),
    mcq(
        "arrays-mcq-007", "advanced", 95,
        "Why can repeatedly appending to a dynamic array still be amortized O(1)?",
        ["dynamic array", "amortized complexity", "capacity"],
        ["Occasional resizing cost is spread across many appends", "No append ever reallocates", "Each append is O(n²)", "The array uses a linked list"],
        "Occasional resizing cost is spread across many appends",
        "Capacity grows in larger steps, so rare expensive copies are averaged over many inexpensive appends.",
        [
            "Separate the cost of one resizing append from the average over a sequence.",
            "Most appends use already allocated spare capacity.",
            "Amortization distributes occasional copying across many operations.",
        ],
    ),
    code(
        "arrays-code-007", "advanced", 125,
        "Implement a linear search that stores the index of target in found_index, or -1 if absent.",
        ["linear search", "enumerate"],
        "values = [7, 4, 9, 2]\ntarget = 9\nfound_index = -1\n",
        "Loop with enumerate(), assign the matching index, and break.",
        "The search visits values in order and returns index 2 for the supplied target.",
        [
            "Track both each position and value.",
            "Keep -1 unless a comparison succeeds.",
            "Use for index, value in enumerate(values): if value == target: found_index = index; break.",
        ],
    ),
    code(
        "arrays-code-008", "advanced", 140,
        "Rotate values left by k positions, allowing k to be larger than the list length.",
        ["rotation", "modulo", "slicing"],
        "values = [1, 2, 3, 4, 5]\nk = 7\nrotated = []\n",
        "Normalize k with modulo len(values), then concatenate values[k:] and values[:k].",
        "Seven left rotations equal two rotations, producing [3, 4, 5, 1, 2].",
        [
            "A full-length rotation returns to the original arrangement.",
            "Reduce k to an equivalent offset before slicing.",
            "Use k %= len(values), then rotated = values[k:] + values[:k].",
        ],
    ),
]
