from .base import code, mcq


TASKS = [
    mcq(
        "classes-mcq-001", "foundation", 65,
        "What does __init__ usually do in a Python class?",
        ["constructor", "object state"],
        ["Initializes object state", "Deletes the object", "Imports the module", "Creates a loop"],
        "Initializes object state",
        "__init__ runs during instance creation and commonly assigns initial attributes.",
        [
            "Consider when __init__ runs in relation to creating an instance.",
            "Its self parameter refers to the new object.",
            "Choose the option describing preparation of the object's stored data.",
        ],
    ),
    mcq(
        "classes-mcq-003", "foundation", 60,
        "What does self refer to inside an instance method?",
        ["self", "instance"],
        ["The instance receiving the method call", "The class file", "The parent class only", "A global variable"],
        "The instance receiving the method call",
        "self is the conventional parameter bound to the particular instance on which the method is invoked.",
        [
            "Different objects can call the same method.",
            "The parameter lets the method access the caller's attributes.",
            "For person.greet(), self is person.",
        ],
    ),
    code(
        "classes-code-003", "foundation", 85,
        "Create an empty class named Book.",
        ["class definition", "pass"],
        "",
        "Define class Book: and use pass for its body.",
        "A class statement creates the Book type even when its body contains only pass.",
        [
            "Use Python's class keyword.",
            "A syntactically empty block needs a placeholder statement.",
            "Complete class Book: followed by an indented pass.",
        ],
    ),
    code(
        "classes-code-004", "foundation", 90,
        "Create a Counter class whose __init__ sets self.value to 0.",
        ["constructor", "attribute"],
        "class Counter:\n    pass\n",
        "Replace pass with __init__(self) and assign self.value = 0.",
        "Each new Counter instance starts with its own value attribute set to zero.",
        [
            "Initialization belongs in __init__.",
            "Store per-instance state through self.",
            "Use def __init__(self): self.value = __.",
        ],
    ),
    code(
        "classes-code-005", "foundation", 90,
        "Instantiate the provided Person class with name 'Ada' and store it in person.",
        ["instantiation", "constructor call"],
        "class Person:\n    def __init__(self, name):\n        self.name = name\n\nperson = None\n",
        "Call Person('Ada') and assign the returned instance.",
        "Calling the class constructs an instance and passes the supplied name to __init__.",
        [
            "A class is callable to create an object.",
            "Supply the constructor argument after the class name.",
            "Complete person = Person(____).",
        ],
    ),
    mcq(
        "classes-mcq-004", "intermediate", 70,
        "What is the difference between an instance attribute and a class attribute?",
        ["instance attribute", "class attribute"],
        ["Instance attributes belong to one object; class attributes are shared defaults", "They are always identical", "Class attributes exist only inside methods", "Instance attributes cannot change"],
        "Instance attributes belong to one object; class attributes are shared defaults",
        "Instance attributes live on individual objects, while class attributes are resolved through the class unless shadowed.",
        [
            "Ask whether changing one object's value affects other objects.",
            "Attributes assigned through self are normally per instance.",
            "Attributes written directly in the class body serve as shared class-level values.",
        ],
    ),
    mcq(
        "classes-mcq-005", "intermediate", 75,
        "What does @property allow a method to do?",
        ["property", "encapsulation"],
        ["Be accessed with attribute syntax", "Run only once", "Become a class automatically", "Override every parent method"],
        "Be accessed with attribute syntax",
        "@property exposes a getter method through ordinary attribute access.",
        [
            "The decorator changes how callers write the access.",
            "No parentheses are needed at the call site.",
            "A method named total can be read as object.total.",
        ],
    ),
    code(
        "classes-code-001", "intermediate", 90,
        "Create Person with an __init__ that stores a name attribute.",
        ["class", "instance attribute"],
        "class Person:\n    pass\n",
        "Define __init__(self, name) and assign self.name = name.",
        "The constructor stores the supplied name independently on each Person instance.",
        [
            "The constructor receives self plus the supplied name.",
            "Store an instance attribute by assigning to self.name.",
            "Use def __init__(self, name): followed by self.name = __.",
        ],
    ),
    code(
        "classes-code-006", "intermediate", 105,
        "Add an increment method to Counter that increases value by 1 and returns it.",
        ["method", "state mutation"],
        "class Counter:\n    def __init__(self):\n        self.value = 0\n",
        "Define increment(self), update self.value, and return self.value.",
        "Each call mutates the instance's stored value and returns the new count.",
        [
            "The method operates on existing instance state.",
            "Use += 1 before returning.",
            "Add def increment(self): self.value += __; return self.value.",
        ],
    ),
    code(
        "classes-code-007", "intermediate", 110,
        "Add a @property named area to Rectangle that returns width * height.",
        ["property", "computed attribute"],
        "class Rectangle:\n    def __init__(self, width, height):\n        self.width = width\n        self.height = height\n",
        "Decorate area(self) with @property and return self.width * self.height.",
        "The property computes area on access without storing duplicate state.",
        [
            "Area can be derived from existing attributes.",
            "Place the property decorator immediately above the method.",
            "Use @property, def area(self): return self.width * self.height.",
        ],
    ),
    mcq(
        "classes-mcq-006", "advanced", 90,
        "When is __repr__ especially useful?",
        ["repr", "debugging"],
        ["Providing an unambiguous developer-facing representation", "Preventing instance creation", "Making every attribute private", "Deleting unused objects"],
        "Providing an unambiguous developer-facing representation",
        "__repr__ is intended to help developers inspect and debug objects.",
        [
            "Contrast developer inspection with a friendly user message.",
            "The representation appears in containers and interactive sessions.",
            "Choose the purpose related to debugging clarity.",
        ],
    ),
    mcq(
        "classes-mcq-007", "advanced", 95,
        "What does defining __eq__ customize?",
        ["dunder method", "equality"],
        ["How instances compare with ==", "How instances are constructed", "How attributes are deleted", "How modules are imported"],
        "How instances compare with ==",
        "__eq__ supplies the behavior used for value equality comparisons.",
        [
            "The method name corresponds to an operator.",
            "It receives another object to compare.",
            "Think of the expression left == right.",
        ],
    ),
    mcq(
        "classes-mcq-008", "advanced", 100,
        "Why might __slots__ reduce memory use for many simple instances?",
        ["slots", "memory"],
        ["It can avoid a per-instance __dict__", "It compresses method bytecode", "It deletes class attributes", "It converts objects to tuples"],
        "It can avoid a per-instance __dict__",
        "__slots__ declares a fixed attribute layout and can remove the usual instance dictionary overhead.",
        [
            "Ordinary instances often store attributes in a dictionary.",
            "A fixed layout needs less dynamic bookkeeping.",
            "Choose the answer concerning per-instance attribute storage.",
        ],
    ),
    code(
        "classes-code-002", "advanced", 115,
        "Add greet to Person so it returns 'Hello, ' followed by the stored name.",
        ["methods", "state"],
        "class Person:\n    def __init__(self, name):\n        self.name = name\n",
        "Define greet(self) and return a string using self.name.",
        "The method reads existing instance state without modifying it.",
        [
            "An instance method can read the name on self.",
            "Return a string formed from the greeting and self.name.",
            "Complete def greet(self): return 'Hello, ' + ____.",
        ],
    ),
    code(
        "classes-code-008", "advanced", 135,
        "Implement __eq__ for Point so two points are equal when both coordinates match.",
        ["equality", "type check", "dunder method"],
        "class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n",
        "Return isinstance(other, Point) and compare x and y.",
        "The method implements structural equality while safely rejecting unrelated object types.",
        [
            "First ensure the other object is a Point.",
            "Both coordinates must satisfy equality.",
            "Use return isinstance(other, Point) and self.x == other.x and self.y == other.y.",
        ],
    ),
]
