from .base import code, mcq


TASKS = [
    mcq(
        "control-mcq-001", "foundation", 50,
        "Which keyword starts a conditional branch in Python?",
        ["if", "branching"],
        ["if", "loop", "def", "return"],
        "if",
        "The if statement evaluates a condition to decide whether its suite runs.",
        [
            "A conditional branch evaluates a Boolean expression.",
            "The relevant statement is followed by a condition and colon.",
            "Choose the keyword used in ___ condition:.",
        ],
    ),
    mcq(
        "control-mcq-002", "foundation", 55,
        "What values does range(3) produce?",
        ["range", "exclusive stop"],
        ["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "3 only"],
        "0, 1, 2",
        "With one argument, range starts at zero and excludes its stop value.",
        [
            "The default start is zero.",
            "The supplied boundary is not included.",
            "List the integers starting at zero and stopping before three.",
        ],
    ),
    mcq(
        "control-mcq-003", "foundation", 55,
        "What does break do inside a loop?",
        ["break", "loop control"],
        ["Ends the nearest loop immediately", "Skips only the current iteration", "Restarts the loop", "Pauses the program"],
        "Ends the nearest loop immediately",
        "break transfers control to the first statement after the nearest enclosing loop.",
        [
            "Compare break with continue.",
            "The loop does not process further iterations after this statement.",
            "Choose the operation that exits the loop.",
        ],
    ),
    code(
        "control-code-003", "foundation", 75,
        "Print 'positive' when number is greater than zero.",
        ["if", "comparison"],
        "number = 4\n",
        "Use if number > 0: followed by print('positive').",
        "The message is printed only when the comparison evaluates to True.",
        [
            "Use a conditional comparison with zero.",
            "The print call belongs in the indented suite.",
            "Complete if number > __: print('positive').",
        ],
    ),
    code(
        "control-code-004", "foundation", 80,
        "Use a while loop to append 1, 2, and 3 to numbers.",
        ["while", "counter"],
        "numbers = []\nvalue = 1\n",
        "Loop while value <= 3, append it, and increment value.",
        "Updating the counter prevents an infinite loop and produces [1, 2, 3].",
        [
            "The loop condition should remain true through value 3.",
            "Change the counter during every iteration.",
            "Use while value <= 3: numbers.append(value); value += 1.",
        ],
    ),
    mcq(
        "control-mcq-004", "intermediate", 70,
        "What does continue do inside a loop?",
        ["continue", "loop control"],
        ["Skips to the next iteration", "Ends the loop", "Returns from the function", "Repeats the previous iteration"],
        "Skips to the next iteration",
        "continue bypasses the rest of the current loop body and begins the next iteration.",
        [
            "The loop itself remains active.",
            "Only the remaining statements for the current item are skipped.",
            "Contrast the behavior with break.",
        ],
    ),
    mcq(
        "control-mcq-005", "intermediate", 75,
        "When does a loop's else block execute?",
        ["loop else", "break"],
        ["When the loop finishes without break", "After every iteration", "Only when the loop body never runs", "Only after continue"],
        "When the loop finishes without break",
        "A loop else suite runs on normal exhaustion but is skipped when break exits the loop.",
        [
            "The else is linked to how the loop terminates.",
            "Normal exhaustion differs from an early break.",
            "Choose the path where no break occurred.",
        ],
    ),
    mcq(
        "control-mcq-006", "intermediate", 75,
        "What does enumerate(names, start=1) provide?",
        ["enumerate", "iteration"],
        ["Pairs of indexes starting at 1 and values", "Only values after the first", "A sorted copy", "The number of names"],
        "Pairs of indexes starting at 1 and values",
        "enumerate yields a counter together with each iterable value, using the supplied initial counter.",
        [
            "The helper adds position information to iteration.",
            "The start argument changes the first counter value.",
            "It can be unpacked as for index, name in enumerate(...).",
        ],
    ),
    code(
        "control-code-001", "intermediate", 65,
        "Write a for loop that prints numbers 1 through 3.",
        ["for loop", "range"],
        "",
        "Use for number in range(1, 4): print(number).",
        "The stop value 4 is excluded, so the loop prints 1, 2, and 3.",
        [
            "A for loop can consume integers produced by range().",
            "Use an exclusive stop one greater than the last number.",
            "Complete for number in range(__, __): print(number).",
        ],
    ),
    code(
        "control-code-005", "intermediate", 100,
        "Find the first even value in numbers and store it in first_even, or None if absent.",
        ["break", "search", "modulo"],
        "numbers = [3, 7, 8, 10]\nfirst_even = None\n",
        "Loop in order, assign when number % 2 == 0, and break.",
        "The search stops at 8, the first value satisfying the even condition.",
        [
            "Preserve the initial fallback unless a match is found.",
            "Exit immediately after the first match.",
            "Use if number % 2 == 0: first_even = number; break.",
        ],
    ),
    mcq(
        "control-mcq-007", "advanced", 90,
        "Why can a while loop accidentally become infinite?",
        ["while", "termination"],
        ["Its condition never becomes false", "while always ignores break", "Python repeats every loop forever", "range has no stop"],
        "Its condition never becomes false",
        "A while loop relies on its body or external state eventually falsifying the condition.",
        [
            "Focus on the loop's termination condition.",
            "State used by the condition must normally change.",
            "If the condition remains true, normal exhaustion never occurs.",
        ],
    ),
    mcq(
        "control-mcq-008", "advanced", 95,
        "What is short-circuit evaluation in a and b?",
        ["short circuit", "boolean logic"],
        ["b is not evaluated when a is false", "Both operands run twice", "a is converted to a loop", "b always determines the result"],
        "b is not evaluated when a is false",
        "For and, a false left operand already determines the result, so Python skips the right operand.",
        [
            "Ask whether the left operand can determine the final Boolean outcome.",
            "False and anything is false.",
            "The right expression is unnecessary when the left is false.",
        ],
    ),
    code(
        "control-code-002", "advanced", 100,
        "Loop over numbers and store only values greater than 10 in result.",
        ["filtering", "conditionals"],
        "numbers = [4, 12, 9, 18]\nresult = []\n",
        "Use an if statement inside a loop and append matching numbers.",
        "The filtered result is [12, 18].",
        [
            "Visit every number but append selectively.",
            "Compare each value with the threshold inside the loop.",
            "Use if number > 10: result.append(number).",
        ],
    ),
    code(
        "control-code-006", "advanced", 125,
        "Generate all coordinate pairs (x, y) for x in 1..2 and y in 1..3.",
        ["nested loops", "cartesian product"],
        "pairs = []\n",
        "Use nested loops over range(1, 3) and range(1, 4), appending tuples.",
        "The outer loop combines each x with all three y values, producing six pairs.",
        [
            "A Cartesian product needs one loop inside another.",
            "Append one tuple during each inner iteration.",
            "Use for x in range(1, 3): for y in range(1, 4): pairs.append((x, y)).",
        ],
    ),
    code(
        "control-code-007", "advanced", 135,
        "Determine whether target is prime using a loop and store the Boolean in is_prime.",
        ["prime test", "loop else", "break"],
        "target = 29\nis_prime = target >= 2\n",
        "Test divisors from 2 through int(target ** 0.5); set false and break on divisibility.",
        "A number at least 2 is prime when no divisor up to its square root divides it evenly.",
        [
            "Composite numbers have a factor no greater than their square root.",
            "Stop at the first divisor whose remainder is zero.",
            "Loop range(2, int(target ** 0.5) + 1) and set is_prime = False on a match.",
        ],
    ),
]
