from .base import code, mcq


TASKS = [
    mcq(
        "exceptions-mcq-001", "foundation", 65,
        "Which block runs whether or not an exception happens?",
        ["finally", "control flow"],
        ["finally", "if", "else", "break"],
        "finally",
        "The finally suite runs after try processing in both success and failure paths.",
        [
            "Look for the exception-handling block intended for cleanup.",
            "It runs after try and except processing.",
            "Choose the keyword that guarantees cleanup execution.",
        ],
    ),
    mcq(
        "exceptions-mcq-003", "foundation", 60,
        "Which exception is raised by int('hello')?",
        ["ValueError", "conversion"],
        ["ValueError", "KeyError", "IndexError", "NameError"],
        "ValueError",
        "The string is a valid object of the expected type but has an invalid value for integer conversion.",
        [
            "The conversion function exists and receives a string.",
            "The string's content cannot represent an integer.",
            "Choose the exception used for an inappropriate value.",
        ],
    ),
    code(
        "exceptions-code-003", "foundation", 85,
        "Raise ValueError with message 'empty' when name is an empty string.",
        ["raise", "validation"],
        "def validate_name(name):\n    pass\n",
        "Check name == '' and raise ValueError('empty').",
        "The function rejects the empty sentinel explicitly with a meaningful exception.",
        [
            "Test the invalid condition before normal processing.",
            "Create the exception in a raise statement.",
            "Use if name == '': raise ValueError('empty').",
        ],
    ),
    code(
        "exceptions-code-004", "foundation", 90,
        "Catch division by zero and store None in result.",
        ["try", "except", "ZeroDivisionError"],
        "a = 10\nb = 0\nresult = 0\n",
        "Place a / b in try and catch ZeroDivisionError.",
        "The specific handler converts an invalid division outcome into the requested fallback.",
        [
            "The risky operation belongs in a try block.",
            "Catch the specific arithmetic exception rather than every exception.",
            "Use except ZeroDivisionError: result = None.",
        ],
    ),
    code(
        "exceptions-code-005", "foundation", 90,
        "Use try/except to read scores['Ada'], storing 0 if the key is absent.",
        ["KeyError", "fallback"],
        "scores = {'Grace': 90}\nresult = None\n",
        "Read with square brackets in try and catch KeyError.",
        "A missing dictionary key triggers KeyError, which the handler maps to zero.",
        [
            "Square-bracket dictionary access can fail for an absent key.",
            "Use the exception type associated with missing keys.",
            "Try result = scores['Ada']; except KeyError: result = 0.",
        ],
    ),
    mcq(
        "exceptions-mcq-004", "intermediate", 75,
        "What does an else block attached to try/except do?",
        ["try else", "control flow"],
        ["Runs when the try block raises no exception", "Runs only after finally", "Catches all exceptions", "Repeats the try block"],
        "Runs when the try block raises no exception",
        "The try-else suite separates success-path work from the protected operation.",
        [
            "It is not an additional exception handler.",
            "Its execution depends on the try block succeeding.",
            "Choose the branch for the no-exception path.",
        ],
    ),
    mcq(
        "exceptions-mcq-005", "intermediate", 80,
        "Why is except Exception usually preferable to a bare except?",
        ["exception hierarchy", "safe handling"],
        ["It avoids swallowing system-exiting exceptions", "It catches fewer application errors than ValueError", "It automatically logs errors", "It retries the operation"],
        "It avoids swallowing system-exiting exceptions",
        "Catching Exception handles ordinary application errors without intercepting BaseException subclasses such as KeyboardInterrupt.",
        [
            "A bare handler catches more than normal application failures.",
            "Some signals should usually be allowed to stop the program.",
            "Exception excludes certain control-flow and system-exit exceptions.",
        ],
    ),
    code(
        "exceptions-code-001", "intermediate", 95,
        "Wrap a file read in try/except and return 'failed' if opening raises an error.",
        ["try", "except", "OSError"],
        "def read_name(path):\n    pass\n",
        "Catch OSError and return the fallback string.",
        "File-system failures are handled without treating successful reads as failures.",
        [
            "The operation that may fail belongs in try.",
            "Use an operating-system-related exception for file opening.",
            "Try returning open(path).read(); except OSError: return 'failed'.",
        ],
    ),
    code(
        "exceptions-code-006", "intermediate", 105,
        "Parse text as an integer; return -1 for invalid text and always set cleaned_up to True.",
        ["ValueError", "finally"],
        "def parse(text):\n    cleaned_up = False\n    result = None\n    return result, cleaned_up\n",
        "Use try/except ValueError for conversion and finally to set cleaned_up.",
        "The finally block records cleanup on both successful and invalid conversions.",
        [
            "Separate conversion, fallback, and unconditional cleanup.",
            "int() raises ValueError for invalid numeric text.",
            "Use finally: cleaned_up = True before returning both values.",
        ],
    ),
    code(
        "exceptions-code-007", "intermediate", 110,
        "Re-raise a caught ValueError after storing its message in error_message.",
        ["re-raise", "exception message"],
        "error_message = ''\ntry:\n    int('bad')\nexcept ValueError as error:\n    pass\n",
        "Set error_message = str(error), then use raise with no argument.",
        "A bare raise inside the handler preserves the original exception and traceback.",
        [
            "Bind the exception object and convert it to text.",
            "Re-raising should not construct a different exception.",
            "Replace pass with error_message = str(error) followed by raise.",
        ],
    ),
    mcq(
        "exceptions-mcq-006", "advanced", 95,
        "What does exception chaining with raise NewError() from original preserve?",
        ["exception chaining", "cause"],
        ["The explicit underlying cause", "Only the new traceback line", "The return value", "Every local variable forever"],
        "The explicit underlying cause",
        "The from clause records a causal link so diagnostics show both abstraction levels.",
        [
            "One exception is translated into another.",
            "Good diagnostics should retain why the new failure occurred.",
            "The original exception becomes the new exception's explicit cause.",
        ],
    ),
    mcq(
        "exceptions-mcq-007", "advanced", 100,
        "Why should custom application exceptions usually inherit Exception?",
        ["custom exception", "hierarchy"],
        ["So ordinary handlers can catch them without treating them as system exits", "So they cannot carry messages", "So Python retries automatically", "So they become warnings"],
        "So ordinary handlers can catch them without treating them as system exits",
        "Exception is the conventional base for recoverable application-level errors.",
        [
            "Choose a base within the normal error-handling hierarchy.",
            "BaseException also includes signals applications rarely intercept.",
            "Custom recoverable failures should behave like other Exception subclasses.",
        ],
    ),
    mcq(
        "exceptions-mcq-008", "advanced", 105,
        "What happens if finally executes return while an exception is active?",
        ["finally", "return", "suppressed exception"],
        ["The return can suppress the exception", "The return is ignored", "Python raises SyntaxError", "The exception always wins"],
        "The return can suppress the exception",
        "Control flow from finally can replace a pending exception, which is why returning there is dangerous.",
        [
            "finally runs while the exception is still pending.",
            "A new control-flow decision can replace the pending outcome.",
            "Consider whether return leaves any exception to propagate.",
        ],
    ),
    code(
        "exceptions-code-002", "advanced", 115,
        "Raise ValueError when age is below zero; otherwise return age.",
        ["raise", "validation"],
        "def validate_age(age):\n    pass\n",
        "Use if age < 0: raise ValueError(...), then return age.",
        "Only negative ages follow the exceptional path.",
        [
            "Validate the invalid case before returning.",
            "Compare age with zero and construct ValueError.",
            "Use if age < 0: raise ValueError(...); return age.",
        ],
    ),
    code(
        "exceptions-code-008", "advanced", 135,
        "Define InvalidScoreError and raise it when score is outside 0 through 100.",
        ["custom exception", "validation"],
        "class InvalidScoreError(Exception):\n    pass\n\ndef validate_score(score):\n    pass\n",
        "Check not 0 <= score <= 100 and raise InvalidScoreError; otherwise return score.",
        "The custom type gives callers a precise application-level failure to catch.",
        [
            "The valid interval includes both boundaries.",
            "Negate the chained range comparison for the invalid path.",
            "Use if not 0 <= score <= 100: raise InvalidScoreError(...).",
        ],
    ),
]
