from .base import code, mcq


TASKS = [
    mcq(
        "inheritance-mcq-001", "foundation", 65,
        "What is a subclass?",
        ["subclass", "parent class"],
        ["A class based on another class", "A loop inside a class", "A dictionary key", "A syntax error"],
        "A class based on another class",
        "A subclass inherits behavior and can specialize a parent class.",
        [
            "Think about the relationship created when one class inherits from another.",
            "The new class can reuse or specialize parent behavior.",
            "Choose the description of a class derived from an existing class.",
        ],
    ),
    mcq(
        "inheritance-mcq-003", "foundation", 60,
        "In class Dog(Animal), which class is the parent?",
        ["inheritance syntax", "parent class"],
        ["Animal", "Dog", "Both are parents", "Neither class"],
        "Animal",
        "The class named in parentheses is the base or parent class.",
        [
            "Inspect the name inside the parentheses.",
            "Dog is being defined, while the other class is reused.",
            "The base class in this declaration is Animal.",
        ],
    ),
    mcq(
        "inheritance-mcq-004", "foundation", 65,
        "What can a subclass use without redefining it?",
        ["inherited method", "reuse"],
        ["A public method inherited from its parent", "A local variable from any function", "Every method from unrelated classes", "A deleted attribute"],
        "A public method inherited from its parent",
        "Inheritance makes parent behavior available to subclass instances unless it is overridden.",
        [
            "The purpose of inheritance includes behavior reuse.",
            "Focus on members supplied by the parent class.",
            "A subclass instance can call an inherited method directly.",
        ],
    ),
    code(
        "inheritance-code-002", "foundation", 90,
        "Create Car as a subclass of Vehicle with no additional behavior.",
        ["subclass syntax", "pass"],
        "class Vehicle:\n    pass\n\n",
        "Define class Car(Vehicle): followed by pass.",
        "The declaration establishes the inheritance relationship even with an empty body.",
        [
            "Put the parent class in parentheses.",
            "Use pass as the placeholder body.",
            "Complete class Car(____): pass.",
        ],
    ),
    code(
        "inheritance-code-003", "foundation", 95,
        "Create a Cat subclass of Animal and instantiate it as pet.",
        ["subclass", "instantiation"],
        "class Animal:\n    pass\n\npet = None\n",
        "Define Cat(Animal), then assign pet = Cat().",
        "pet becomes an instance of Cat and is also an instance of Animal.",
        [
            "First declare the child class using the parent name.",
            "Then call the child class to construct an object.",
            "Use class Cat(Animal): pass and pet = Cat().",
        ],
    ),
    mcq(
        "inheritance-mcq-002", "intermediate", 75,
        "Which concept lets a subclass replace behavior from its parent?",
        ["override", "polymorphism"],
        ["Overriding", "Indexing", "Hashing", "Slicing"],
        "Overriding",
        "A subclass overrides a method by defining a method with the same name.",
        [
            "The child redefines inherited behavior.",
            "The replacement method has the same name as the parent's method.",
            "Choose the object-oriented term for method replacement.",
        ],
    ),
    mcq(
        "inheritance-mcq-005", "intermediate", 75,
        "What is super() commonly used for?",
        ["super", "parent method"],
        ["Calling parent-class behavior", "Creating a global variable", "Preventing inheritance", "Converting an object to a string"],
        "Calling parent-class behavior",
        "super() provides access to the next implementation in the method resolution order.",
        [
            "A subclass may want to extend rather than discard parent behavior.",
            "The helper delegates to an ancestor implementation.",
            "It is often seen as super().__init__(...).",
        ],
    ),
    mcq(
        "inheritance-mcq-006", "intermediate", 80,
        "What does isinstance(dog, Animal) return when Dog inherits Animal?",
        ["isinstance", "subtype"],
        ["True", "False", "Only true if Dog has no methods", "It raises TypeError"],
        "True",
        "A subclass instance is also considered an instance of its ancestor classes.",
        [
            "Inheritance establishes an is-a relationship.",
            "The check includes the object's class and its ancestors.",
            "A Dog is an Animal for isinstance checks.",
        ],
    ),
    code(
        "inheritance-code-004", "intermediate", 110,
        "Override describe in Book so it returns 'book' instead of the Item result.",
        ["override", "method"],
        "class Item:\n    def describe(self):\n        return 'item'\n\nclass Book(Item):\n    pass\n",
        "Define describe(self) inside Book and return 'book'.",
        "The subclass method is selected when describe is called on a Book.",
        [
            "Use the same method name as the parent.",
            "Place the replacement inside Book.",
            "Replace pass with def describe(self): return 'book'.",
        ],
    ),
    code(
        "inheritance-code-005", "intermediate", 115,
        "Extend Employee.__init__ in Manager by storing department as well as name.",
        ["super", "constructor", "extension"],
        "class Employee:\n    def __init__(self, name):\n        self.name = name\n\nclass Manager(Employee):\n    pass\n",
        "Call super().__init__(name), then assign self.department.",
        "The parent initializes inherited state and Manager adds its specialized attribute.",
        [
            "Avoid duplicating the parent's name assignment.",
            "Delegate parent initialization with super().",
            "Define __init__(self, name, department), call super().__init__(name), then store department.",
        ],
    ),
    mcq(
        "inheritance-mcq-007", "advanced", 95,
        "What determines which method Python selects in multiple inheritance?",
        ["MRO", "multiple inheritance"],
        ["The method resolution order", "Alphabetical class names", "Object creation time", "The number of attributes"],
        "The method resolution order",
        "Python follows the class's MRO, based on C3 linearization, to search for methods.",
        [
            "Multiple parents require a deterministic search order.",
            "Python exposes this order through Class.mro().",
            "Choose the answer naming the resolution sequence.",
        ],
    ),
    mcq(
        "inheritance-mcq-008", "advanced", 100,
        "Why should cooperative multiple-inheritance methods usually call super()?",
        ["cooperative inheritance", "super", "MRO"],
        ["So every implementation in the MRO can participate", "To skip all parent methods", "To disable polymorphism", "To make attributes immutable"],
        "So every implementation in the MRO can participate",
        "Cooperative super() calls pass control along the MRO rather than naming one parent directly.",
        [
            "Consider a chain containing more than one parent implementation.",
            "Hard-coding one parent can bypass another class.",
            "super() advances to the next method in the MRO.",
        ],
    ),
    code(
        "inheritance-code-001", "advanced", 120,
        "Create Dog as an Animal subclass that overrides speak to return 'woof'.",
        ["inheritance", "override"],
        "class Animal:\n    def speak(self):\n        return 'sound'\n",
        "Define class Dog(Animal) and override speak.",
        "Calling Dog().speak() uses the subclass implementation and returns 'woof'.",
        [
            "Place the parent class name in parentheses.",
            "Define speak with the same signature inside Dog.",
            "Complete class Dog(Animal): def speak(self): return 'woof'.",
        ],
    ),
    code(
        "inheritance-code-006", "advanced", 135,
        "Implement a cooperative TimestampMixin.describe that adds 'timestamped ' before the next describe result.",
        ["mixin", "super", "cooperative method"],
        "class TimestampMixin:\n    pass\n",
        "Define describe(self) and return 'timestamped ' + super().describe().",
        "The mixin contributes behavior while allowing the next MRO class to supply the base description.",
        [
            "A cooperative mixin delegates rather than choosing a concrete parent.",
            "Call the next describe through super().",
            "Return 'timestamped ' + super().describe().",
        ],
    ),
    code(
        "inheritance-code-007", "advanced", 145,
        "Create FlyingFish from Fish and Flyer, then store its method-resolution class names in order.",
        ["multiple inheritance", "MRO"],
        "class Fish:\n    pass\n\nclass Flyer:\n    pass\n\n",
        "Define class FlyingFish(Fish, Flyer), then use [cls.__name__ for cls in FlyingFish.mro()].",
        "The resulting order begins FlyingFish, Fish, Flyer, object.",
        [
            "List both parents in the class declaration.",
            "Every class exposes its resolution order through mro().",
            "Build names = [cls.__name__ for cls in FlyingFish.mro()].",
        ],
    ),
]
