from .base import code, mcq


TASKS = [
    mcq(
        "lists-mcq-001", "foundation", 55,
        "What does append() do to a Python list?",
        ["append", "mutation"],
        ["Adds an item to the end", "Deletes the last item", "Sorts the list", "Creates a new tuple"],
        "Adds an item to the end",
        "append() mutates the existing list by placing one supplied object at its end.",
        [
            "Think about whether append() mutates the existing list or creates a different collection.",
            "After calling the method with one value, the list length grows by exactly one.",
            "For items = [1, 2], items.append(3) makes items[-1] equal to 3.",
        ],
    ),
    mcq(
        "lists-mcq-002", "foundation", 50,
        "Which index reads the first item of a non-empty Python list?",
        ["indexing", "zero-based index"],
        ["0", "1", "-1", "len(items)"],
        "0",
        "Python sequences use zero-based indexing, so the first element is at index 0.",
        [
            "Python counts sequence positions from zero.",
            "The second item has index 1, so move one position earlier.",
            "For items = ['a', 'b'], items[0] is 'a'.",
        ],
    ),
    mcq(
        "lists-mcq-003", "foundation", 55,
        "What does values[1:3] select?",
        ["slicing", "exclusive stop"],
        ["Indexes 1 and 2", "Indexes 1, 2, and 3", "Only index 3", "The first three indexes"],
        "Indexes 1 and 2",
        "A slice includes its start index and excludes its stop index.",
        [
            "Recall that a slice has a start and a stop boundary.",
            "The start is included, while the stop is not.",
            "For ['a', 'b', 'c', 'd'], [1:3] produces ['b', 'c'].",
        ],
    ),
    code(
        "lists-code-001", "foundation", 75,
        "Create a list named evens containing the even numbers from 2 to 8.",
        ["list literal", "sequence"],
        "evens = []\n",
        "Use a list literal or range with a step of 2.",
        "A valid result contains 2, 4, 6, and 8 in order.",
        [
            "An even number is divisible by 2; include the requested endpoints 2 and 8.",
            "You can write the four values directly or use range() with a step of 2.",
            "A useful scaffold is evens = list(range(__, __, __)); range's stop is exclusive.",
        ],
    ),
    code(
        "lists-code-003", "foundation", 70,
        "Start with colors = ['red', 'blue'] and add 'green' to the end.",
        ["append", "mutation"],
        "colors = ['red', 'blue']\n",
        "Call colors.append('green').",
        "append() changes colors in place and adds the new string as its final element.",
        [
            "Use a list method that adds one object.",
            "The method should be called on colors and does not require reassignment.",
            "Complete colors.____('green').",
        ],
    ),
    mcq(
        "lists-mcq-004", "intermediate", 65,
        "How is extend([3, 4]) different from append([3, 4])?",
        ["extend", "append", "iteration"],
        ["extend adds two elements; append adds one nested list", "They are identical", "extend sorts the list", "append removes duplicates"],
        "extend adds two elements; append adds one nested list",
        "extend iterates over its argument, while append treats the entire argument as one object.",
        [
            "Consider how many new top-level elements each operation contributes.",
            "One method consumes an iterable; the other accepts one object.",
            "[1, 2].extend([3, 4]) becomes four flat items, unlike append.",
        ],
    ),
    mcq(
        "lists-mcq-005", "intermediate", 70,
        "What is the result of [x for x in range(6) if x % 2 == 0]?",
        ["list comprehension", "filtering", "modulo"],
        ["[0, 2, 4]", "[1, 3, 5]", "[2, 4, 6]", "[0, 1, 2, 3, 4, 5]"],
        "[0, 2, 4]",
        "The condition retains values in range(6) whose remainder after division by 2 is zero.",
        [
            "range(6) produces values from 0 through 5.",
            "The condition keeps only values divisible by two.",
            "Test 0, 1, 2, 3, 4, and 5 against x % 2 == 0.",
        ],
    ),
    mcq(
        "lists-mcq-006", "intermediate", 70,
        "Which expression creates a new reversed list without modifying items?",
        ["slicing", "copy", "reversal"],
        ["items[::-1]", "items.reverse()", "items.sort()", "reversed = items.reverse()"],
        "items[::-1]",
        "A slice with step -1 creates a reversed copy; reverse() mutates and returns None.",
        [
            "Look for an expression rather than an in-place method.",
            "A negative slice step walks a sequence backward.",
            "Use the full slice form with a step of -1.",
        ],
    ),
    code(
        "lists-code-002", "intermediate", 95,
        "Build a list named squares with the squares of numbers 1 through 5.",
        ["iteration", "comprehension"],
        "squares = []\n",
        "Use [n * n for n in range(1, 6)] or an equivalent loop.",
        "The resulting list is [1, 4, 9, 16, 25].",
        [
            "The square of a number n is n * n.",
            "Iterate from 1 through 5; range's stop value is excluded.",
            "Complete squares = [n * n for n in range(__, __)].",
        ],
    ),
    code(
        "lists-code-004", "intermediate", 100,
        "Create unique containing the values from items without duplicates, preserving first-seen order.",
        ["deduplication", "membership", "iteration"],
        "items = [3, 1, 3, 2, 1]\nunique = []\n",
        "Loop through items and append a value only when it is not already in unique.",
        "An order-preserving solution produces [3, 1, 2].",
        [
            "Build the answer incrementally rather than converting directly to an unordered set.",
            "Before appending each value, test membership in unique.",
            "Use: for item in items: if item not in unique: unique.append(item).",
        ],
    ),
    mcq(
        "lists-mcq-007", "advanced", 85,
        "After b = a and b.append(4), why does a also contain 4?",
        ["aliasing", "references", "mutation"],
        ["a and b reference the same list", "append copies both lists", "Python synchronizes variable names", "Lists are immutable"],
        "a and b reference the same list",
        "Assignment copies the reference, not the list, so both names point to the same mutable object.",
        [
            "Distinguish copying a value from copying a reference.",
            "Mutation is visible through every name bound to the same object.",
            "Check whether b = a creates any new list object.",
        ],
    ),
    mcq(
        "lists-mcq-008", "advanced", 90,
        "Why can matrix.copy() still share inner rows with matrix?",
        ["shallow copy", "nested lists", "references"],
        ["It copies only the outer list", "copy() never creates a list", "Rows are immutable", "It converts rows to tuples"],
        "It copies only the outer list",
        "A shallow copy duplicates the outer container while retaining references to nested mutable objects.",
        [
            "Focus on the difference between the outer list and its elements.",
            "A shallow operation does not recursively duplicate nested objects.",
            "Changing copied[0][0] can reach the row object also stored in matrix.",
        ],
    ),
    code(
        "lists-code-005", "advanced", 120,
        "Rotate items one position to the right and store the new list in rotated.",
        ["slicing", "rotation"],
        "items = [1, 2, 3, 4]\nrotated = []\n",
        "Combine the last-item slice with the slice containing all preceding items.",
        "A one-position right rotation produces [4, 1, 2, 3] without mutating items.",
        [
            "The final item must become the first item.",
            "Use two slices and concatenate them.",
            "Complete rotated = items[-1:] + items[____].",
        ],
    ),
    code(
        "lists-code-006", "advanced", 130,
        "Split values into consecutive groups of size 3 and store them in chunks.",
        ["slicing", "chunking", "range"],
        "values = [1, 2, 3, 4, 5, 6, 7]\nchunks = []\n",
        "Iterate over start indexes in steps of 3 and append values[start:start + 3].",
        "The final shorter group is retained, producing [[1, 2, 3], [4, 5, 6], [7]].",
        [
            "Each chunk is a slice beginning at a multiple of three.",
            "range() can advance the start index by the chunk size.",
            "Use for start in range(0, len(values), 3): chunks.append(values[start:start + 3]).",
        ],
    ),
    code(
        "lists-code-007", "advanced", 140,
        "Transpose the rectangular matrix so rows become columns and store the result in transposed.",
        ["nested lists", "transpose", "comprehension"],
        "matrix = [[1, 2, 3], [4, 5, 6]]\ntransposed = []\n",
        "For each column index, collect that index from every row.",
        "The transposed result is [[1, 4], [2, 5], [3, 6]].",
        [
            "The output needs one row for each original column.",
            "Use the length of matrix[0] for column indexes and read row[column].",
            "Build [[row[col] for row in matrix] for col in range(len(matrix[0]))].",
        ],
    ),
]
